# Config for single device full finetuning in train_qwen_imagenet.py
# using a Qwen2.5 0.5B
#
# This config assumes that you've run the following command before launching:
#   tune download Qwen/Qwen2.5-0.5B
#
# To launch on a single device, run the following command from root:
#   tune run train_qwen_imagenet.py --config train_qwen_imagenet.yaml
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training:
#   tune run train_qwen_imagenet.py --config train_qwen_imagenet.yaml checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.

gpu_type: A100
output_dir: /tmp/torchtune/qwen2_5_0_5B/imagenet_cosmos_di8x8 # /tmp may be deleted by your system. Change it to your preference.

# Model arguments
model:
  _component_: torchtune.models.qwen2_5.qwen2_5_0_5b

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen2_5.qwen2_5_tokenizer
  path: /tmp/Qwen2.5-0.5B/vocab.json
  merges_file: /tmp/Qwen2.5-0.5B/merges.txt
  max_seq_len: null

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen2.5-0.5B
  checkpoint_files: [model.safetensors]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN2
resume_from_checkpoint: False

# Dataset
dataset:
  column: cosmos_di8x8_tokens
  packed: False  # True increases speed
  max_seq_len: 512
seed: 0
shuffle: True

# Fine-tuning arguments
epochs: 1
max_steps_per_epoch: null
batch_size: 16
gradient_accumulation_steps: 1  # Use to increase effective batch size
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  lr: 5e-4
optimizer_in_bwd: False  # True saves memory. Requires gradient_accumulation_steps=1
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Training env
device: cuda

# Memory management / performance
enable_activation_checkpointing: False  # True reduces memory
enable_activation_offloading: False  # True reduces memory
dtype: bf16
clip_grad_norm: null
compile: False  # torch.compile the model + loss, True increases speed + decreases memory

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.TensorBoardLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True

# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
